# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4b3ad45a2756aa4dc5527e182e1b8d85341d2e220e020baa03314fd6424cb81b104ecf578b86c2b155713c8b5cd1b46c08523f572b3c6af00b98837dd968a6e

test:
  secret_key_base: ddf054910a298d8ad8579fc54e548a8dbe2e45f91b0339fff3158e43b0c20a435c714bbee35502fdc3dd7a04d4ac50a5a78f42fd876f2e271969f49a6a6cc690

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
